### ISSUE TITLE
exclusion_regions.txt should be named by the ref it connects to

### ISSUE THREAD

**Issue by mp15** [gabraham/flashpca#14]
Hi,

Given GRCh38 is now entering wider use but GRCh37 is still in use by many projects it might be worthwhile renaming exclusion_regions.txt to exclusion_regions_grch37.txt or similar. That way we know which coordinate system is intended.

**Comment by gabraham** [comment]
Thanks Martin, that's a good idea.

**Comment by gabraham** [comment]
I've renamed it exclusion_regions_hg19.txt.
