### ISSUE TITLE
Feature request: projection PCA

### ISSUE THREAD

**Issue by mp15** [gabraham/flashpca#15]
We frequently project other data onto a PCA calculated by 1000 genomes. Would it be possible to add projection PCAs to flashPCA please?

**Comment by gabraham** [comment]
How are you doing this at the moment?

**Comment by mp15** [comment]
Currently we are using plink with --pca-cluster-names to specify which clusters to use in calculating the principle components. We also use --read-freq to load the MAFs used in the relationship matrix calculation so they are based on only samples in those clusters.

**Comment by gabraham** [comment]
@mp15 are you doing PCA on a dataset _combined_ with the 1000G data, but basing the PCA on just the 1000G data, or doing it in two steps, first do PCA on 1000G to get PCs etc, then a separate projection of your own data?

**Comment by gabraham** [comment]
Will be addressed in v2.0
