### ISSUE TITLE
Can flashpca take a covariance matrix like the eigen in R does?

### ISSUE THREAD

**Issue by SiyangLiu** [gabraham/flashpca#28]
Hi Gabraham,
I have a pre-computed covariance matrix. Can flashpca take a covariance matrix like the eigen in R does? 
I will really appreciate your reply. Thank you very much in advance. 

Best,
Siyang

**Comment by gabraham** [comment]
@SiyangLiu 
No, flashpca can't take a covariance matrix, the main idea is to avoid creating that matrix in the first place since it can be very large. But the RSpectra package should be able to do eigen-decomposition on that (you'll need to scale it appropriately yourself).
