### ISSUE TITLE
Help installing flashpcaR

### ISSUE THREAD

**Issue by sharvari14** [gabraham/flashpca#31]
Hi,

I am trying to install ‘flashpcaR’ library, but get this message instead.

package ‘flashpcaR’ is not available (for R version 3.4.1) 

I’ve also tried:

>  p <- "https://github.com/gabraham/flashpca/releases/download/v1.2.5/flashpcaR_1.2.5.tgz"
> install.packages(p, contriburl=NULL, type="source")
..
Warning message:
package ‘https://github.com/gabraham/flashpca/releases/download/v1.2.5/flashpcaR_1.2.5.tgz’ is not available (for R version 3.4.0) 

Could you please help which version to use for 3.4.

Thanks
Sharvari

**Comment by privefl** [comment]
See https://github.com/gabraham/flashpca#installation.

For example, I use `devtools::install_github("gabraham/flashpca/flashpcaR")`.
