### ISSUE TITLE
R CMD build flashpcaR fails

### ISSUE THREAD

**Issue by Smooge123** [gabraham/flashpca#33]
I get:
Error: processing vignette 'flashpcaR.Rmd' failed with diagnostics:
invalid regular expression '(?<!(^|
)``)`r[ #]([^`]+)\s*`', reason 'Invalid regexp'
Execution halted
---
  Anyone know a fix?

Steve

**Comment by privefl** [comment]
Installing with `devtools::install_github("gabraham/flashpca/flashpcaR")` works fine on my computer.
