### ISSUE TITLE
flashpcaR should return PVE

### ISSUE THREAD

**Issue by gabraham** [gabraham/flashpca#35]
Proportion of variance explained is computed but not returned in the R function

**Comment by jmf11** [comment]
Is there is a plan to add this feature any time soon? Is it kosher to calculate directly from the eigenvalues?

**Comment by gabraham** [comment]
@jmf11 yes we're working on this, hopefully available soon.

Re calculating from the eigenvalues, how are you doing that?

**Comment by jmf11** [comment]
Re calculating variance from eigenvalues. In the adegenet package tutorial for dudi.pca, they show that the variance of the eigenvectors equals the eigenvalues. See p. 26

http://adegenet.r-forge.r-project.org/files/PRstats/practical-MVAintro.1.0.pdf

So percentage of total variation explained by PC1, for example, could be calculated as (eigenvalue 1) / sum(eigenvalue1..n) * 100.

**Comment by gabraham** [comment]
Ah ok, the issue with that method is that flashpca doesn't typically compute all the eigenvalues (only top few), so you can't compute the denominator. But there is another way which flashpca uses (computing the sum of squares of the matrix X, i.e., the trace of XX^T).

**Comment by gabraham** [comment]
@jmf11 this is fixed in the latest version on github
