### ISSUE TITLE
flashpcaR install error

### ISSUE THREAD

**Issue by mercedes-colomar** [gabraham/flashpca#36]
Installed all pre-reqs as per instructions then installed flashpcaR with:

`devtools::install_github("gabraham/flashpca/flashpcaR")`

This resulted in a failed install with the following output:

...
/usr/local/installed/R/3.6.0/lib64/R/library/RSpectra/include/Spectra/MatOp/internal/ArnoldiOp.h: In instantiation of ‘void Spectra::ArnoldiOp<Scalar, OpType, Spectra::IdentityBOp>::perform_op(const Scalar*, Scalar*) [with Scalar = double; OpType = SVDWide]’:

/usr/local/installed/R/3.6.0/lib64/R/library/RSpectra/include/Spectra/LinAlg/Lanczos.h:101:13:   required from ‘void Spectra::Lanczos<Scalar, ArnoldiOpType>::factorize_from(int, int, int&) [with Scalar = double; ArnoldiOpType = Spectra::ArnoldiOp<double, SVDWide, Spectra::IdentityBOp>]’
/usr/local/installed/R/3.6.0/lib64/R/library/RSpectra/include/Spectra/SymEigsBase.h:334:9:   required from ‘int Spectra::SymEigsBase<Scalar, SelectionRule, OpType, BOpType>::compute(int, Scalar, int) [with Scalar = double; int SelectionRule = 3; OpType = SVDWide; BOpType = Spectra::IdentityBOp]’
randompca.cpp:136:29:   required from here
/usr/local/installed/R/3.6.0/lib64/R/library/RSpectra/include/Spectra/MatOp/internal/ArnoldiOp.h:142:9: error: invalid conversion from ‘const double*’ to ‘double*’ [-fpermissive]
         m_op.perform_op(x_in, y_out);
         ^
In file included from randompca.cpp:13:0:
svdwide.h:30:12: note: initializing argument 1 of ‘void SVDWide::perform_op(double*, double*)’
       void perform_op(double *x_in, double* y_out);
            ^
In file included from /usr/local/installed/R/3.6.0/lib64/R/library/RSpectra/include/Spectra/SymEigsBase.h:20:0,
                 from /usr/local/installed/R/3.6.0/lib64/R/library/RSpectra/include/Spectra/SymEigsSolver.h:12,
                 from randompca.h:24,
                 from randompca.cpp:11:
/usr/local/installed/R/3.6.0/lib64/R/library/RSpectra/include/Spectra/MatOp/internal/ArnoldiOp.h: In instantiation of ‘void Spectra::ArnoldiOp<Scalar, OpType, Spectra::IdentityBOp>::perform_op(const Scalar*, Scalar*) [with Scalar = double; OpType = SVDWideOnline]’:
/usr/local/installed/R/3.6.0/lib64/R/library/RSpectra/include/Spectra/LinAlg/Lanczos.h:101:13:   required from ‘void Spectra::Lanczos<Scalar, ArnoldiOpType>::factorize_from(int, int, int&) [with Scalar = double; ArnoldiOpType = Spectra::ArnoldiOp<double, SVDWideOnline, Spectra::IdentityBOp>]’
/usr/local/installed/R/3.6.0/lib64/R/library/RSpectra/include/Spectra/SymEigsBase.h:334:9:   required from ‘int Spectra::SymEigsBase<Scalar, SelectionRule, OpType, BOpType>::compute(int, Scalar, int) [with Scalar = double; int SelectionRule = 3; OpType = SVDWideOnline; BOpType = Spectra::IdentityBOp]’
randompca.cpp:178:29:   required from here
/usr/local/installed/R/3.6.0/lib64/R/library/RSpectra/include/Spectra/MatOp/internal/ArnoldiOp.h:142:9: error: invalid conversion from ‘const double*’ to ‘double*’ [-fpermissive]
         m_op.perform_op(x_in, y_out);
         ^
In file included from randompca.cpp:13:0:
svdwide.h:81:12: note: initializing argument 1 of ‘void SVDWideOnline::perform_op(double*, double*)’
       void perform_op(double *x_in, double* y_out);
            ^
make: *** [randompca.o] Error 1
ERROR: compilation failed for package ‘flashpcaR’
removing ‘/usr/local/installed/R/3.6.0/lib64/R/library/flashpcaR’
Error in i.p(...) :

**Comment by gabraham** [comment]
Please see comments to issue #37, should be fixed by now on master branch.
