### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by drwhitehouse** [gabraham/flashpca#39]
I'm trying to build master with the latest spectra.
I'm using gcc/7.1.0 boost/1.68.0 & eigen/3.3.4

Build fails with:

```
>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'                                                                                      
flashpca.o:(.rodata._ZTVN5boost15program_options11typed_valueIdcEE[_ZTVN5boost15program_options11typed_valueIdcEE]+0x40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >
const&, bool) const'
collect2: error: ld returned 1 exit status
make: *** [flashpca] Error 1
```

Any help would be appreciated.

**Comment by gabraham** [comment]
I think there is some incompatibility with Boost, need to look at this further

**Comment by drwhitehouse** [comment]
Apologies, it may actually be the case that output above was generated by using boost version 1.63.0.

I have tried again, this time explicitly with boost 1.68.0 and get a very similar result:

```
>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
flashpca.o:(.rodata._ZTVN5boost15program_options11typed_valueIdcEE[_ZTVN5boost15program_options11typed_valueIdcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
collect2: error: ld returned 1 exit status
make: *** [flashpca] Error 1
```

Those two versions of boost are all we have at the moment. I'll see if we can build another.
I can provide more output if its useful.

**Comment by gabraham** [comment]
@drwhitehouse I have tried compiling on Ubuntu 19.04, g++ version 8.3, Spectra 0.8.1, Eigen 3.3.7, and boost 1.70, and everything compiles fine.

Perhaps try `make clean` first?

**Comment by drwhitehouse** [comment]
Aah. We don't have either boost 1.67 or Eigen 3.3.7. 
I think it might be better to build this as a Singularity container.

Thanks for your help.

**Comment by gabraham** [comment]
@drwhitehouse I don't think you need specifically boost 1.67 or Eigen 3.3.7, these are just examples of more recent versions that seem to work. But try to see if these work for you.
