### ISSUE TITLE
error: no matching function for call to ‘RandomPCA::scca

### ISSUE THREAD

**Issue by preetilk** [gabraham/flashpca#47]
make all
g++ -Ispectra/include -I/usr/local/include/boost -I/usr/local/include/eigen -march=native -std=c++0x -O3 -DNDEBUG -DVERSION=\"2.1\" -funroll-loops -ftree-vectorize -ffast-math -fopenmp -c flashpca.cpp -o flashpca.o
flashpca.cpp: In function ‘int main(int, char**)’:
flashpca.cpp:716:30: error: no matching function for call to ‘RandomPCA::scca(Data&, double&, double&, long int&, int&, long long int&, int&, double&, unsigned int&)’
      maxiter, tol, block_size);
                              ^
In file included from flashpca.cpp:23:0:
randompca.h:81:12: note: candidate: void RandomPCA::scca(Eigen::MatrixXd&, Eigen::MatrixXd&, double, double, long int, unsigned int, unsigned int, double)
       void scca(MatrixXd &X, MatrixXd &Y, double lambda1, double lambda2,
            ^~~~
randompca.h:81:12: note:   candidate expects 8 arguments, 9 provided
randompca.h:84:12: note: candidate: void RandomPCA::scca(Eigen::MatrixXd&, Eigen::MatrixXd&, double, double, long int, unsigned int, unsigned int, double, Eigen::MatrixXd&)
       void scca(MatrixXd &X, MatrixXd &Y, double lambda1, double lambda2,
            ^~~~
randompca.h:84:12: note:   no known conversion for argument 1 from ‘Data’ to ‘Eigen::MatrixXd& {aka Eigen::Matrix<double, -1, -1>&}’
randompca.h:87:12: note: candidate: void RandomPCA::scca(Data&, double, double, long int, unsigned int, unsigned int, double, unsigned int)
       void scca(Data &dat, double lambda1, double lambda2,
            ^~~~
randompca.h:87:12: note:   candidate expects 8 arguments, 9 provided
randompca.h:91:12: note: candidate: void RandomPCA::scca(Data&, double, double, long int, unsigned int, unsigned int, double, unsigned int, Eigen::MatrixXd&)
       void scca(Data &dat, double lambda1, double lambda2,
            ^~~~
randompca.h:91:12: note:   no known conversion for argument 9 from ‘unsigned int’ to ‘Eigen::MatrixXd& {aka Eigen::Matrix<double, -1, -1>&}’
make: *** [flashpca.o] Error 1

**Comment by gabraham** [comment]
@preetilk should be fixed in latest master branch.
