### ISSUE TITLE
incorrect reading of .bed file

### ISSUE THREAD

**Issue by MikeDMorgan** [gabraham/flashpca#9]
Analyzing and reading of a .bed file is massively underestimating the number of SNPs, leading to garbage output.  These are data-post LD pruning.

flashpca --numthreads 28  --seed 23421  --bfile /ifs/projects/proj045/pipeline_gwas_genotypes/genome.dir/WholeGenome  --ndim 20  --stand binom  --method eigen  --v  --outpc /ifs/projects/proj045/pipeline_gwas_genotypes/pca.dir/WholeGenome_naive.pcs  --outvec /ifs/projects/proj045/pipeline_gwas_genotypes/pca.dir/WholeGenome_naive.eigenvec  --outload /ifs/projects/proj045/pipeline_gwas_genotypes/pca.dir/WholeGenome_naive.loadings  --outval  /ifs/projects/proj045/pipeline_gwas_genotypes/pca.dir/WholeGenome_naive.eigenval  --outpve /ifs/projects/proj045/pipeline_gwas_genotypes/pca.dir/WholeGenome_naive.pve   --outmeansd  /ifs/projects/proj045/pipeline_gwas_genotypes/pca.dir/WholeGenome_naive.meansd

[Thu Nov 19 11:32:29 2015] Start flashpca (git version )
[Thu Nov 19 11:32:29 2015] Using 28 OpenMP threads
[Thu Nov 19 11:32:29 2015] seed: 23421
[Thu Nov 19 11:32:29 2015] Detected pheno file /ifs/projects/proj045/pipeline_gwas_genotypes/genome.dir/WholeGenome.fam, 152732 samples
[Thu Nov 19 11:32:30 2015] Analyzing BED file '/ifs/projects/proj045/pipeline_gwas_genotypes/genome.dir/WholeGenome.bed', found **5028 SNPs**
[Thu Nov 19 11:32:30 2015] Reading BED file '/ifs/projects/proj045/pipeline_gwas_genotypes/genome.dir/WholeGenome.bed'
^C

From Plinkv1.9:
PLINK v1.90b3v 64-bit (15 Jul 2015)        https://www.cog-genomics.org/plink2
(C) 2005-2015 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to test_freq.log.
Options in effect:
  --bfile /ifs/projects/proj045/pipeline_gwas_genotypes/genome.dir/WholeGenome
  --freq
  --out test_freq

387555 MB RAM detected; reserving 193777 MB for main workspace.
Allocated 81749 MB successfully, after larger attempt(s) failed.
**117512** variants loaded from .bim file.
152732 people (71774 males, 80958 females) loaded from .fam.
137178 phenotype values loaded from .fam.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 152732 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is 0.990655.
--freq: Allele frequencies (founders only) written to test_freq.frq .

**Comment by gabraham** [comment]
Thanks for reporting this Mike. This may be some integer overflow issue due to the massive size of your data. Which version is this?

**Comment by MikeDMorgan** [comment]
I'm running v1.1.2.1.  I have run this previously with ~60K SNPs on a slightly smaller data set and got sensible results.

**Comment by gabraham** [comment]
OK, I will try to reproduce this with my data.

**Comment by gabraham** [comment]
@MikeDMorgan what Linux kernel version are you using? (from uname -a)

**Comment by MikeDMorgan** [comment]
We're running SL6 on top of version 2.6.32 Linux kernel:
Linux cgat150.anat.ox.ac.uk 2.6.32-573.7.1.el6.x86_64 #1 SMP Thu Sep 10 13:42:16 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gabraham** [comment]
Could you send your email address to gad.abraham@unimelb.edu.au? I've got a different version for you to test but I github won't let me attach it here.

**Comment by MikeDMorgan** [comment]
Using the statically linked version, and a smaller .bed file (m=108582 SNPs), it very quickly throughs a memory error:
  flashpca_x86-64 --bfile flashpca_test   --mem low --tol 1e-3  --numthreads 24   --v  --outpc flashpca_GA_test
[Fri Nov 20 13:33:31 2015] arguments: flashpca flashpca_x86-64 --bfile flashpca_test --mem low --tol 1e-3 --numthreads 24 --v --outpc flashpca_GA_test 
[Fri Nov 20 13:33:31 2015] Start flashpca (version 1.2)
[Fri Nov 20 13:33:31 2015] Using 24 OpenMP threads
[Fri Nov 20 13:33:31 2015] seed: 1
[Fri Nov 20 13:33:31 2015] Detected pheno file flashpca_test.fam, 152732 samples
[Fri Nov 20 13:33:31 2015] Analyzing BED file 'flashpca_test.bed', found 108582 SNPs
[Fri Nov 20 13:33:31 2015] Reading BED file 'flashpca_test.bed'
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

This doesn't appear to be an issue with any of the options, i.e. number of threads, mem usage, tolerance.

**Comment by MikeDMorgan** [comment]
This latest error appears to be a problem with the .bed file itself (called genotypes).  I have tested it with another dataset and it reads the .bed file fine (derived from imputed genotypes).  The files are not corrupt; they can be correctly and succesfully read by  plink1.9 (stable and Nov 11 development release) and GCTA v1.25.0.

**Comment by gabraham** [comment]
Thanks. It's simply running out of memory, since flashpca loads all the genotypes into RAM. Could you try a smaller subset, just to check that the original issue of incorrect number of SNPs reported is fixed? Perhaps cut the number of SNPs down by half for this, depending on how much RAM you have.

I'll leave the memory issue for another time, it actually requires a fundamental change in how the PCA is computed, along the lines of fastPCA in EIGENSOFT6 (streaming PCA).

**Comment by gabraham** [comment]
This is fixed in v1.2.2.
